export const MAX_LEN_NAMES = 40;
export const MAX_LEN_COMPANY_NAME = 50;
export const MAX_LEN_KNOWN_VISITOR_MESSAGE = 100;

export const MAX_LEN_FRAME_EXAMPLE_QUESTION = 60;
export const MAX_FRAME_EXAMPLE_QUESTIONS = 5;

export const MAX_LEN_FRAME_INSTRUCTIONS = 100;
export const MAX_ROW_FRAME_INSTRUCTIONS = 3;
